# Generated by Django 4.0.3 on 2022-03-19 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_decription_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
